# Pulldown Y SNPs with OY SNPs

In [12]:
import numpy as np
import os  # For Saving to Folder
import pandas as pd
import matplotlib.pyplot as plt

import socket
import os as os
import sys as sys
import multiprocessing as mp
from pysam import AlignmentFile

### For Arial Font
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'   # Set the defaul
### Make sure to have the font installed (it is on cluster for Harald)
rcParams['font.sans-serif'] = ['Arial']

socket_name = socket.gethostname()
print(socket_name)

if socket_name.startswith("compute-"):
    print("HSM Computational partition detected.")
    path = "/n/groups/reich/hringbauer/git/y_chrom/"  # The Path on Midway Cluster
    
elif socket_name.startswith("bionc") or socket_name.startswith("hpc"):
    print("Leipzig Cluster detected!")
    path = "/mnt/archgen/users/hringbauer/git/y_chrom/"
    
else:
    raise RuntimeWarning("Not compatible machine. Check!!")

os.chdir(path)  # Set the right Path (in line with Atom default)

# Show the current working directory. Should be HAPSBURG/Notebooks/ParallelRuns
print(os.getcwd())
print(f"CPU Count: {mp.cpu_count()}")
print(sys.version)

### Custom Imports
from python.pulldown import load_snp_file_ISOGG, call_y_bam, mismatch_path

hpc030
Leipzig Cluster detected!
/mnt/archgen/users/hringbauer/git/y_chrom
CPU Count: 128
3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]

# 0) Prepare Data

### 0a) Load Autorun Eager Dictionary mapping iids to bam files

In [2]:
dft = pd.read_csv("/mnt/archgen/users/hringbauer/git/auto_popgen/output/TF/v0.3/bam_paths.tsv", sep="\t")
dft2 = pd.read_csv("/mnt/archgen/users/hringbauer/git/auto_popgen/output/RM/v0.3/bam_paths.tsv", sep="\t")
n = np.sum(dft["bam#"]>0)
bam_dict = dict(zip(dft["iid"], dft["bam_path"]))
bam_dict2 = dict(zip(dft2["iid"], dft2["bam_path"]))
print(f"Loaded {len(dft)} Individuals. With BAM: {n}")
print(f"Loaded {len(dft2)} RM Individuals.")

Loaded 28636 Individuals. With BAM: 17215
Loaded 4607 RM Individuals.

### 0b) Prepare SNP List

In [3]:
df = load_snp_file_ISOGG("./data/all_snps.csv")

Index(['Name', 'Subgroup Name', 'Alternate Names', 'rs numbers',
       'Build 37 Number', 'Build 38 Number', 'Mutation Info'],
      dtype='object')
Loaded 92035 SNPs
# Positions available: 91881
# Biallelic SNPs: 91814
# Ref & Alt different: 91811
# Ref & Alt ACTG: 91806
# Unique SNP positions: 73148

In [28]:
df1 = pd.read_csv("/mnt/archgen/users/hringbauer/git/y_chrom/data/all_snps_filtered_levels.csv", low_memory=False)
print(f"Loaded {len(df1)} OY SNPs with levels loaded")

Loaded 2868884 OY SNPs with levels loaded

In [9]:
df1.head()

,Unnamed: 0,SNP-ID,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level
0,1557478,FTG48817,Y,16259936.0,G,T,NaN,NaN,0
1,1557470,MF630222,Y,16259923.0,T,G,NaN,NaN,0
2,1557471,FT415097,Y,16259925.0,C,T,NaN,NaN,0
3,1557472,FTE94401,Y,16259927.0,C,T,NaN,NaN,0
4,2527307,FTC61890,Y,22705984.0,G,C,NaN,NaN,0

### Create BED file for OY [1x requirement]

In [25]:
savepath = "./data/OY_snps.bed"

dft = df1.sort_values(by="pos")
dft = dft[["chrom", "pos"]].copy()

dft["pos1"] = dft["pos"]
dft.to_csv(savepath, sep="\t", index=False, header=None)
print(f"Saved {len(dft)} OY SNPs to {savepath}")

Saved 2868884 OY SNPs to ./data/OY_snps.bed

### 1) Run Y Calling

### 1a) Single Example with ISOGG SNPs

In [62]:
%%time
path_bam = bam_dict2["KKG002"]

df_ch, df_der = call_y_bam(df=df, 
                           path_bam=path_bam) #A55903 and A55904
len(df_der)

Average Coverage: 5.1489x
#Sites covered: 58158/73148
#Derived Loci:
1030 / 58158 covered>0
CPU times: user 99.5 ms, sys: 2.7 ms, total: 102 ms
Wall time: 2.57 s

1030

In [63]:
df_der[-100:-50]

### This sample is J2a1a1b1a - looks like 2 SNPs are derived there

,Name,chrom,pos,ref,alt,Subgroup Name,Alternate Names,rs numbers,A,C,G,T,ref#,alt#
930,PF4965,Y,15610713,G,T,J2a,CTS4360,NaN,0,0,0,10,0,10
931,CTS4699,Y,15775488,A,G,J2a,PF4909,NaN,0,0,3,0,0,3
932,PF4966,Y,15704139,C,T,J2a,CTS4540,NaN,0,0,0,5,0,5
933,F841,Y,6854256,C,T,J2a,PF4948,NaN,0,0,0,5,0,5
934,CTS9538,Y,18952077,G,A,J2a,PF4919,NaN,1,0,0,0,0,1
935,L505,Y,21970721,G,T,J2a,PF4987,NaN,0,0,0,1,0,1
936,PF4953,Y,7680253,C,G,J2a,NaN,NaN,0,0,6,0,0,6
937,PF4952,Y,7676739,C,T,J2a,NaN,NaN,0,0,0,7,0,7
938,PF5112,Y,23033706,C,T,J2a1,CTS11251,NaN,0,0,0,1,0,1
939,PF4610,Y,22757708,G,C,J2a1,NaN,NaN,0,3,0,0,0,3
940,CTS4403,Y,15632637,G,T,J2a1,PF5096,NaN,0,0,0,7,0,7
941,PF5104,Y,20816211,G,C,J2a1,NaN,NaN,0,8,0,2,0,8
942,PF5105,Y,20836109,A,G,J2a1,NaN,NaN,0,0,9,0,0,9
943,F1227,Y,8465758,C,G,J2a1,NaN,NaN,0,0,14,0,0,14
944,PF5091,Y,8809001,T,C,J2a1,NaN,NaN,0,2,0,0,0,2
945,CTS10711,Y,22715995,C,T,J2a1a,PF5109,NaN,0,0,0,5,0,5
946,FGC2794,Y,7910634,A,G,J2a1a,Z7728;_S10814,NaN,0,0,4,0,0,4
947,CTS2192,Y,14213941,G,A,J2a1a,PF5094,NaN,2,0,0,0,0,2
948,Z1849,Y,8482151,G,T,J2a1a,PF5089,NaN,0,0,0,15,0,15
949,PF5106,Y,21493159,G,A,J2a1a,NaN,NaN,3,0,0,0,0,3
950,PF5114,Y,23402887,A,G,J2a1a,CTS11983,NaN,1,0,6,0,1,6
951,PF4901,Y,9422558,C,A,J2a1a,NaN,NaN,9,0,0,0,0,9
952,S396,Y,23021978,A,G,J2a1a,F4326;_L27;_PF5111,NaN,0,0,2,0,0,2
953,PF5088,Y,8107430,T,C,J2a1a1,NaN,NaN,0,2,0,0,0,2
954,Y20305,Y,17392251,G,A,J2a1a1a2b2a3b1b2~,FGC43940,NaN,1,0,0,0,0,1
955,AM01358,Y,23141753,A,T,J2a1a1b,AMM342;_PF5163;_Z2222,NaN,0,0,0,5,0,5
956,PF5160,Y,8265737,G,A,J2a1a1b,Z2221,NaN,2,0,0,0,0,2
957,PF5197,Y,19068737,G,A,J2a1a1b1,Z2397,NaN,6,0,0,0,0,6
958,PF5172,Y,7882829,G,A,J2a1a1b1a,NaN,NaN,7,0,0,0,0,7
959,PF5190,Y,17873156,G,A,J2a1a1b1a,NaN,NaN,4,0,0,0,0,4
960,PF4984,Y,21534723,G,A,J2a1a~,NaN,NaN,3,0,0,0,0,3
961,PF5090,Y,8678907,C,T,J2a1a~,NaN,NaN,0,0,0,1,0,1
962,PF4899,Y,8827398,A,T,J2a~,NaN,NaN,0,0,0,1,0,1
963,PF4928,Y,21553644,G,A,J2a~,NaN,NaN,4,0,0,0,0,4
964,PF4957,Y,8420738,G,C,J2a~,F1183,NaN,0,5,0,1,0,5
965,PF4962,Y,14628068,T,C,J2a~,F1810,NaN,0,7,0,1,1,7
966,Z7760,Y,16739675,C,T,J2a~,FGC2795,NaN,0,0,0,1,0,1
967,Z604,Y,16725162,C,T,J2b2a~,AM01366,NaN,0,0,0,1,0,1
968,PF5100,Y,17614366,G,A,J_(Notes),CTS7683;_P354,NaN,10,0,0,0,0,10
969,Z20369^,Y,9457920,C,T,L1a1,NaN,NaN,0,0,0,1,0,1
970,M2476,Y,14472683,G,A,L1a2,NaN,NaN,1,0,0,0,0,1
971,M5710,Y,16900247,A,G,L1a2,NaN,NaN,0,0,2,0,0,2
972,Z20299^,Y,22181078,C,T,L1a2a1a,NaN,NaN,0,0,0,1,0,1
973,Z30984,Y,14194554,C,T,M1,NaN,NaN,0,0,0,1,0,1
974,Z30926,Y,7992575,C,T,M1,NaN,NaN,0,0,0,1,0,1
975,Z4846^,Y,7855600,T,C,N1a1a1a1a,M2208^,NaN,0,1,0,0,0,1
976,Z35264,Y,15238418,G,A,N1a1a1a1a1a2a1a2b1~,NaN,NaN,1,0,0,0,0,1
977,CTS9460,Y,18907504,G,A,N1a1a1a1a2a1a1a1a1a1a1d~,NaN,NaN,1,0,0,0,0,1
978,Z4878,Y,9915300,G,A,N1a1a1a1a2a1a1a1b,NaN,NaN,1,0,0,0,0,1
979,YP5796,Y,17431587,T,G,N1a1a3~,NaN,NaN,0,0,1,0,0,1

In [61]:
s = "J2a1a1b1a"
mismatch_path(s, df_ch).sort_values(by="Subgroup Name")[-50:]

Mismatches: 0 / 0

Empty DataFrame
Columns: [Subgroup Name, chrom, pos, ref, alt, Y-haplogroup, YFull translation, Level, A, C, G, T, ref#, alt#]
Index: []

### 1b) Try OY SNPs

In [65]:
%%time
path_bam = bam_dict2["KKG002"]

df_ch, df_der = call_y_bam(df=df1, path_bam=path_bam,
                           path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed') 
len(df_der)

Average Coverage: 1.3794x
#Sites covered: 907725/2868884
#Derived Loci:
6981 / 907725 covered>0
CPU times: user 1.28 s, sys: 432 ms, total: 1.71 s
Wall time: 22.7 s

6981

In [66]:
df_der.sort_values(by="Level")[-50:]

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
6617,Y6453,Y,8250772,G,A,R-Y6453,NaN,51,1,0,0,0,0,1
236,A39534,Y,18881152,G,A,R-FTF86763,NaN,51,1,0,0,0,0,1
3743,FTG77865,Y,18089187,G,A,N-FTG77668,NaN,51,1,0,0,0,0,1
7,A1234,Y,14975852,C,T,R-A1234,NaN,51,0,0,0,1,0,1
2383,FT157294,Y,15925461,G,A,J-FT157054,NaN,51,1,0,0,0,0,1
2981,FTA59569,Y,7510363,C,T,R-FTA59569,NaN,52,0,0,0,1,0,1
2971,FTA56456,Y,7834060,G,A,R-FTA81373,NaN,52,1,0,0,0,0,1
2571,FT278583,Y,22512323,G,A,J-BY55828,NaN,52,1,0,0,0,0,1
2724,FT378570,Y,23299264,G,A,R-FT377470,NaN,52,1,0,0,0,0,1
799,BY83284,Y,10036953,G,A,R-BY77186,NaN,52,1,0,0,0,0,1
6510,Y47083,Y,8305301,C,T,R-BY97424,NaN,52,0,0,0,1,0,1
2865,FT67041,Y,6984284,G,A,R-FT68865,NaN,52,1,0,0,0,0,1
2494,FT23209,Y,17096551,C,T,R-BY197966,NaN,52,0,0,0,1,0,1
2637,FT33115,Y,3501182,C,T,R-BY202860,NaN,52,0,0,0,1,0,1
2279,FGC75588,Y,23631385,G,A,J-FGC75579,NaN,52,1,0,0,0,0,1
311,BY102987,Y,15625468,C,T,R-BY60507,NaN,52,0,1,0,2,1,2
19,A16490,Y,23164042,C,T,R-BY73979,NaN,52,0,0,0,1,0,1
294,ALK642,Y,7958253,C,T,R-FT370810,NaN,52,0,0,0,1,0,1
285,A996,Y,9759795,G,A,R-A991,NaN,53,1,0,0,0,0,1
6633,Y66271,Y,14242488,G,A,R-BY135342,NaN,53,1,0,0,0,0,1
1925,FGC14693,Y,18240337,G,A,R-FTF7866,NaN,53,1,0,0,0,0,1
2567,FT275124,Y,22187340,T,C,R-Y567118,NaN,53,0,1,0,0,0,1
2394,FT167495,Y,7735583,G,A,T-FT167495,NaN,53,1,0,0,0,0,1
364,BY1188,Y,15583361,A,C,R-BY1188,NaN,53,0,1,0,0,0,1
513,BY176806,Y,14954153,G,A,R-FT83699,NaN,54,1,0,0,0,0,1
5538,S6875,Y,22567774,C,T,R-S6875,NaN,54,0,2,0,3,2,3
2481,FT226494,Y,9461072,G,A,R-FT227340,NaN,54,1,0,0,0,0,1
419,BY146385,Y,23570888,C,T,R-BY62083,NaN,54,0,0,0,1,0,1
2907,FTA13363,Y,23184944,C,T,J-FTA13363,NaN,54,0,0,0,1,0,1
2741,FT384958,Y,15975975,G,A,J-FT384251,NaN,55,1,0,0,0,0,1
2546,FT26209,Y,22825804,C,T,R-FT20138,NaN,55,0,0,0,1,0,1
547,BY191731,Y,21465439,C,T,R-BY191578,NaN,55,0,0,0,1,0,1
746,BY63736,Y,7183581,G,A,R-BY72222,NaN,55,1,0,0,0,0,1
6716,Y86329,Y,8271622,C,T,T-Y86329,NaN,55,0,0,0,1,0,1
2369,FT149805,Y,21116994,C,T,R-FT149425,NaN,55,0,1,0,3,1,3
3118,FTB6763,Y,14209992,C,T,R-FTB6208,NaN,55,0,0,0,1,0,1
3762,FTG92125,Y,22156390,G,A,R-FTG91998,NaN,55,1,0,0,0,0,1
138,A24138,Y,22105110,G,A,R-A24131,NaN,56,1,0,0,0,0,1
2790,FT41101,Y,9385817,G,A,R-FT41021,NaN,56,1,0,0,0,0,1
686,BY3355,Y,16443268,C,A,R-BY3354,NaN,56,4,0,0,0,0,4
3365,FTD4565,Y,6347260,C,T,R-FTC66400,NaN,56,0,0,0,1,0,1
3172,FTC13238,Y,17089716,G,A,R-FTC13238,NaN,57,1,0,0,0,0,1
261,A672,Y,8876605,G,A,R-A672,NaN,57,1,0,0,0,0,1
2493,FT22981,Y,16776873,G,A,R-FT20207,NaN,57,1,0,0,0,0,1
2313,FT107554,Y,13835245,G,A,R-FT108202,NaN,57,1,0,0,0,0,1
2875,FT73421,Y,17367712,G,A,R-A2208,NaN,57,1,0,0,0,0,1
5539,S6895,Y,23960292,G,A,R-S6893,NaN,59,1,0,0,0,0,1
3440,FTD99014,Y,17892995,C,T,R-FTD99014,NaN,59,0,0,0,1,0,1
720,BY50003,Y,17350559,C,T,R-BY50003,NaN,60,0,0,0,1,0,1
2537,FT25615,Y,21721852,G,A,R-FT25605,NaN,62,1,0,0,0,0,1

In [67]:
dfc = df_der.groupby("Y-haplogroup").agg(
    n=('Y-haplogroup', 'count'),
    level=('Level', 'mean')).reset_index()
dfc2 = dfc[dfc["n"]>1] # Only extract Y haplogroups that have 2 SNPs derived

In [68]:
dfc2.sort_values(by="level")[-50:]

         Y-haplogroup    n  level
0               A-AF6    7    0.0
136          F-F21819    3    0.0
367          J-Page28   11    0.0
361            J-M304    2    0.0
447          O-F22068    2    0.0
617         R-BY74074    2    0.0
4             A-L1090   60    2.0
3             A-L1085   12    2.0
11             A-V168    5    3.0
17       A00-FGC26001    2    3.0
10             A-V148    3    3.0
12             A-V221    2    4.0
6               A-M31   29    4.0
16           A-Z11282    2    5.0
30             BT-M42    2    5.0
15            A-Y8284    7    5.0
49            CT-M168    7    6.0
31             BT-M91  245    6.0
41               C-V9   29    7.0
48            CF-P143    3    7.0
28            B-V1108    2    8.0
139             F-M89  104    8.0
173  GHIJK-YSC0001299    2    9.0
1          A-BY160926    2    9.0
141          F-Y60086    8   10.0
52         D-FT172198    2   10.0
272           IJK-L15    4   11.0
138            F-M427    3   11.0
26              B-PH5    2   12.0
270           IJ-P124    3   12.0
271           IJ-P125    2   12.0
110              E-M2    2   14.0
363            J-M410   52   15.0
360             J-L26   13   17.0
133          E-Z36730    2   19.0
386           J-Z2221    2   19.0
365          J-PF5172    2   21.0
299        J-FT104353    2   22.0
370         J-Y153763    2   23.0
432          N-SK1508    5   26.0
146         G-BY96310    2   28.0
493            Q-M958    2   29.0
441           O-F1234    2   30.0
462          O-SK1608    2   30.0
921          T-Y19196    2   32.0
442          O-F15948    4   38.0

In [87]:
df_der[df_der["Y-haplogroup"]=="J-PF5172"]

Empty DataFrame
Columns: [Subgroup Name, chrom, pos, ref, alt, Y-haplogroup, YFull translation, Level, A, C, G, T, ref#, alt#]
Index: []

In [85]:
df_der[df_der["Subgroup Name"]=="J-Y153763"]

Empty DataFrame
Columns: [Subgroup Name, chrom, pos, ref, alt, Y-haplogroup, YFull translation, Level, A, C, G, T, ref#, alt#]
Index: []

In [81]:
df_der[df_der["Subgroup Name"].str.contains("PF5190")]

Empty DataFrame
Columns: [Subgroup Name, chrom, pos, ref, alt, Y-haplogroup, YFull translation, Level, A, C, G, T, ref#, alt#]
Index: []

The Y-Haplogroup seems to be J-Y153763. It is two G->A, but the parent haplogroup, PF5172, also has two G-A derived.

# 2) Run Henry II

In [78]:
%%time
path_bam = "/mnt/archgen/Autorun_eager/eager_outputs/SG/BMG/BMG001/trimmed_bam/BMG001_ss_libmerged_udghalf.trimmed.bam"

df_ch, df_der = call_y_bam(df=df1, path_bam=path_bam,
                           path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed')

Average Coverage: 0.3605x
#Sites covered: 813297/2868884
#Derived Loci:
3469 / 813297 covered>0
CPU times: user 1.23 s, sys: 308 ms, total: 1.54 s
Wall time: 19.2 s

3469

In [89]:
dfc = df_der.groupby("Y-haplogroup").agg(
    n=('Y-haplogroup', 'count'),
    level=('Level', 'mean')).reset_index()
dfc2 = dfc[dfc["n"]>1] # Only extract Y haplogroups that have 2 SNPs derived

In [102]:
dfc.sort_values(by="level")[-50:] R-FTA98646 and R-FTF30738

    Y-haplogroup  n  level
321       R-L196  1   46.0
258   R-FGC14769  1   46.0
312   R-FTE20211  1   46.0
207   R-BY103964  1   47.0
216   R-BY172590  1   47.0
242    R-BY77606  1   47.0
282   R-FT371843  1   47.0
252    R-BY99994  1   47.0
247    R-BY95411  1   47.0
238    R-BY68473  1   47.0
268   R-FGC76329  1   47.0
303   R-FTB62702  1   47.0
269    R-FT12729  1   48.0
240    R-BY73349  1   48.0
284   R-FT380550  1   48.0
309   R-FTD22903  1   48.0
271   R-FT145882  1   48.0
344     R-Y93683  1   48.0
220    R-BY20294  1   49.0
300   R-FTB39768  1   49.0
343     R-Y86922  1   49.0
261     R-FGC440  1   49.0
173    N-FT36349  1   49.0
129    J-BY11327  1   49.0
248    R-BY99072  1   49.0
138   J-FT273396  1   50.0
170   N-BY174348  1   50.0
211    R-BY16148  1   51.0
295   R-FTA73557  1   51.0
272   R-FT193543  1   51.0
229     R-BY3536  1   51.0
206   R-BY101530  1   51.0
213   R-BY167399  1   52.0
278   R-FT256131  1   52.0
177     N-Y21582  1   53.0
275    R-FT21237  1   53.0
270   R-FT135117  1   53.0
179     N-Y71293  1   53.0
243    R-BY78034  1   54.0
249    R-BY99237  1   54.0
314   R-FTE67343  1   54.0
264   R-FGC54628  1   54.0
251    R-BY99469  1   54.0
217   R-BY173170  1   55.0
310   R-FTD38219  1   56.0
273   R-FT199058  1   56.0
263   R-FGC47650  1   56.0
304   R-FTB71436  1   56.0
244    R-BY78411  1   59.0
257     R-F17060  1   59.0

In [95]:
df_ch[df_ch["Subgroup Name"].str.contains("FTA63331")]

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
844707,FTA63331,Y,8840886,G,T,R-FTA63331,NaN,46,0,0,0,1,0,1

In [112]:
df_ch[df_ch["Y-haplogroup"]=="R-BY78034"] # -FTA63879

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
868616,BY78034,Y,9096231,G,A,R-BY78034,NaN,54,1,0,0,0,0,1
868722,FT412112,Y,23446881,A,G,R-BY78034,NaN,54,1,0,0,0,1,0