# Identify consistent errors and clean them in OY tables

In [60]:
import numpy as np
import os  # For Saving to Folder
import pandas as pd
import matplotlib.pyplot as plt

import socket
import os as os
import sys as sys
import multiprocessing as mp
from pysam import AlignmentFile

### For Arial Font
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'   # Set the defaul
### Make sure to have the font installed (it is on cluster for Harald)
rcParams['font.sans-serif'] = ['Arial']

socket_name = socket.gethostname()
print(socket_name)

if socket_name.startswith("compute-"):
    print("HSM Computational partition detected.")
    path = "/n/groups/reich/hringbauer/git/y_chrom/"  # The Path on Midway Cluster
    
elif socket_name.startswith("bionc") or socket_name.startswith("hpc"):
    print("Leipzig Cluster detected!")
    path = "/mnt/archgen/users/hringbauer/git/y_chrom/"
    
else:
    raise RuntimeWarning("Not compatible machine. Check!!")

os.chdir(path)  # Set the right Path (in line with Atom default)

# Show the current working directory. Should be HAPSBURG/Notebooks/ParallelRuns
print(os.getcwd())
print(f"CPU Count: {mp.cpu_count()}")
print(sys.version)

### Custom Imports
from python.pulldown import load_snp_file_ISOGG, call_y_bam, mismatch_path, div_anc_der, get_mismatch_snps, create_parent_dct

hpc030
Leipzig Cluster detected!
/mnt/archgen/users/hringbauer/git/y_chrom
CPU Count: 128
3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0]

### 0) Load data for calls

In [72]:
### Load OY SNPs
df1 = pd.read_csv("/mnt/archgen/users/hringbauer/git/y_chrom/data/all_snps_filtered_levels.csv", low_memory=False)
print(f"Loaded {len(df1)} OY SNPs with levels loaded")

### Load OY node dictionary
chpar = create_parent_dct()

### Load "faulty" SNPs to exclude from summary stats
df_cts = pd.read_csv("/mnt/archgen/users/eric_garcia/OYdb/mm12_v3.tsv", sep="\t")
df_ex = df_cts[df_cts["count"]>5] # SNPs that are ancestral in at least 3/12 test sample derived chains

Loaded 2868884 OY SNPs with levels loaded

In [68]:
df1[df1["Y-haplogroup"]=="G-FT49621"]

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level
2361590,FT50940,Y,18386312,T,C,G-FT49621,NaN,22
2361784,FT51496,Y,22868752,A,G,G-FT49621,NaN,22
2362008,FT48839,Y,3686342,G,T,G-FT49621,NaN,22
2362348,FT50003,Y,9908291,C,G,G-FT49621,NaN,22
2362349,FT50509,Y,16229182,T,C,G-FT49621,NaN,22
2362706,FT49621,Y,7159646,C,A,G-FT49621,NaN,22
2363227,FT50450,Y,15914961,C,T,G-FT49621,NaN,22
2364039,FT48731,Y,3292432,T,C,G-FT49621,NaN,22
2364687,FT49046,Y,4527953,T,A,G-FT49621,NaN,22
2365272,FT51752,Y,28701880,A,C,G-FT49621,NaN,22
2365583,FT50189,Y,14422000,C,G,G-FT49621,NaN,22
2366286,FT49775,Y,8078902,G,T,G-FT49621,NaN,22
2366467,FT283807,Y,20820114,A,G,G-FT49621,NaN,22
2367234,FT50884,Y,18022880,T,G,G-FT49621,NaN,22
2367456,FT50273,Y,14872665,T,C,G-FT49621,NaN,22
2367587,FT49337,Y,5610557,A,C,G-FT49621,NaN,22
2367700,FT51561,Y,23281400,C,T,G-FT49621,NaN,22
2369541,FT51213,Y,21230859,C,G,G-FT49621,NaN,22
2369573,FT50266,Y,14810500,C,T,G-FT49621,NaN,22
2369629,FT51437,Y,22566965,C,T,G-FT49621,NaN,22
2369919,FT51432,Y,22553143,G,C,G-FT49621,NaN,22
2369962,FT50706,Y,17156612,A,G,G-FT49621,NaN,22

# 1) Do manual calls for 12 samples

In [13]:
df_bams = pd.read_csv("/mnt/archgen/users/hringbauer/git/EPIDEMIC/output/tables/autoeager_seqfull_anno.tsv", sep="\t")
print(f"Loaded {len(df_bams)} processed bam files from PTN")

Loaded 414 processed bam files from PTN

In [14]:
### 12 Male individuals in pedigrees
iids = ["PTN209", "PTN211", "PTN139", "PTN146", "PTN267", "PTN238", "PTN126", "PTN406", "PTN231", "PTN495", "PTN390", "PTN439"]
len(iids)

12

In [25]:
for iid in iids:
    print(f"Running IID {iid}...")
    bam_path = df_bams.loc[df_bams["iid"]==iid, "bam"].values[0]

    ### Do the call
    df_ch, df_der = call_y_bam(df=df1, path_bam=bam_path,
                           path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed') 

    ### Post-process output for info for manual call
    dft = div_anc_der(df_ch)
    dfd =dft[dft["Derived"]>dft["Ancestral"]]
    display(dfd.sort_values(by="#DER in par.").tail(20))

Running IID PTN209...
Average Coverage: 7.2976x
#Sites covered: 2370738/2868884
#Derived Loci:
6390 / 2370738 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
84668,R-M269,27,97,0,97,0,29,589
1448,C-V9,7,38,3,35,0,286,656
84564,R-L23,28,3,0,3,0,29,686
84587,R-L51,29,5,0,5,0,29,689
55893,R-BY3293,35,1,0,1,0,43,689
84552,R-L151,31,3,0,3,0,29,694
84890,R-PF6538,31,1,0,1,0,29,694
50798,R-BY1188,53,1,0,1,0,52,697
84558,R-L2,36,1,0,1,0,29,697
56679,R-BY3953,45,1,0,1,0,39,697
55504,R-BY2891,48,1,0,1,0,41,697
84613,R-L706,39,1,0,1,0,41,697
63274,R-FGC59563,37,1,0,1,0,29,698
56191,R-BY3508,38,1,0,1,0,29,698
61492,R-DF90,38,4,0,4,0,29,699
86130,R-Y12051,39,1,0,1,0,29,703
56150,R-BY3490,41,2,0,2,0,29,704
57011,R-BY4233,44,3,0,3,0,29,706
51384,R-BY132832,45,1,0,1,0,29,709
83589,R-FTG53091,46,2,0,2,0,29,710

Running IID PTN211...
Average Coverage: 0.3651x
#Sites covered: 820913/2868884
#Derived Loci:
4017 / 820913 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
55679,R-Y151368,45,1,0,1,0,24,249
41461,R-FT127736,45,1,0,1,0,18,249
56196,R-Y22894,44,1,0,1,0,7,249
45158,R-FT371228,48,1,0,1,0,9,249
54600,R-MF7792,46,1,0,1,0,9,249
38009,R-BY6971,47,1,0,1,0,20,249
35613,R-BY33664,47,1,0,1,0,11,249
58766,R-Z42134,42,1,0,1,0,12,249
58593,R-Z23516,42,1,0,1,0,13,249
42978,R-FT211469,41,1,0,1,0,11,249
32708,R-BY137177,41,1,0,1,0,29,249
41332,R-FT122249,49,1,0,1,0,21,249
49486,R-FTB74107,54,1,0,1,0,13,249
31687,R-BY103865,52,1,0,1,0,11,249
35304,R-BY2891,48,1,0,1,0,10,249
39537,R-DF90,38,1,0,1,0,6,250
36250,R-BY4233,44,1,0,1,0,6,251
53783,R-FTG53091,46,1,0,1,0,6,252
1004,C-V9,7,14,0,14,0,64,254
1230,D-CTS3946,9,1,0,1,0,64,268

Running IID PTN139...
Average Coverage: 0.3297x
#Sites covered: 752016/2868884
#Derived Loci:
3882 / 752016 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
48105,R-FTC3117,55,1,0,1,0,94,147
11214,I-FT235980,32,1,0,1,0,18,185
14769,I-S31,15,8,0,8,0,10,185
10477,I-FGC88432,23,1,0,1,0,18,185
15658,I-Y36690,33,1,0,1,0,19,185
10389,I-FGC52744,46,1,0,1,0,21,185
10212,I-CTS2257,16,4,0,4,0,10,193
14770,I-S33,18,14,1,13,0,10,197
9415,I-BY3095,29,1,0,1,0,40,210
14864,I-Y10720,20,2,0,2,0,11,210
14763,I-S2599,19,2,0,2,0,11,210
9758,I-BY60413,33,1,0,1,0,26,210
14759,I-S2519,22,2,0,2,0,11,212
14483,I-L38,24,13,0,12,1,11,214
14821,I-SK1263,23,1,0,1,0,11,214
918,C-V9,7,16,1,14,1,57,223
14942,I-Y13067,26,1,0,1,0,11,226
14602,I-PH1237,28,2,0,2,0,11,227
14880,I-Y111839,29,1,0,1,0,11,229
12078,I-FT58623,30,3,0,3,0,11,230

Running IID PTN146...
Average Coverage: 0.3544x
#Sites covered: 792820/2868884
#Derived Loci:
4338 / 792820 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
15995,I-Y36065,35,1,0,1,0,12,197
9366,I-BY189317,29,1,0,1,0,17,197
15109,I-S31,15,16,0,16,0,6,197
15842,I-Y29635,37,1,0,1,0,14,197
10891,I-FT124056,33,1,0,1,0,8,197
10444,I-CTS2257,16,5,0,5,0,6,213
16077,I-Y3945,34,1,0,1,0,25,218
9539,I-BY208416,31,1,0,1,0,22,218
15110,I-S33,18,19,1,18,0,6,218
968,C-V9,7,14,1,13,0,54,233
15203,I-Y10720,20,2,0,2,0,7,236
15105,I-S2599,19,1,0,1,0,7,236
16115,I-Y41574,36,1,0,1,0,37,236
12820,I-FTA38856,41,1,0,1,0,27,236
11169,I-FT176008,33,1,0,1,0,34,236
15031,I-S10728,20,1,0,1,0,7,237
15036,I-S11321,21,2,0,1,1,7,238
14814,I-L38,24,16,0,16,0,7,239
15278,I-Y13076,27,1,0,1,0,7,255
12386,I-FT58623,30,1,0,1,0,7,256

Running IID PTN267...
Average Coverage: 0.4835x
#Sites covered: 1004319/2868884
#Derived Loci:
4110 / 1004319 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
23932,J-FTD43091,36,1,0,1,0,67,197
26001,J-Y3082,33,1,0,1,0,55,197
16557,I-M170,14,46,1,45,0,14,197
25985,J-Y304060,34,1,0,1,0,105,197
22844,J-FTA47014,29,1,0,1,0,72,197
24460,J-FTF47360,30,1,0,1,0,31,197
16877,I-S31,15,14,0,14,0,15,242
10286,I-BY167444,24,1,0,1,0,33,242
11657,I-CTS2257,16,10,0,10,0,15,256
16878,I-S33,18,21,1,20,0,15,266
16870,I-S2599,19,1,0,1,0,16,286
16986,I-Y10720,20,1,0,1,0,16,286
16868,I-S2519,22,1,0,1,0,16,287
16537,I-L38,24,21,0,21,0,16,288
1071,C-V9,7,19,1,18,0,95,306
17086,I-Y13067,26,1,0,1,0,16,309
16674,I-PH1237,28,1,0,1,0,16,310
17013,I-Y111839,29,1,0,1,0,16,311
13847,I-FT58623,30,1,0,1,0,16,312
1336,D-CTS3946,9,1,0,1,0,97,324

Running IID PTN238...
Average Coverage: 0.2982x
#Sites covered: 694724/2868884
#Derived Loci:
3436 / 694724 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
22013,J-Y539179,44,1,0,1,0,40,129
22749,J-ZS1824,48,1,0,1,0,40,129
20844,J-HU533,51,1,0,1,0,41,129
17943,J-FT182281,52,1,0,1,0,40,129
19097,J-FTA29896,36,1,0,1,0,47,129
14043,I-M170,14,33,0,33,0,9,129
18553,J-FT366856,29,1,0,1,0,76,129
9693,I-BY70891,23,1,0,1,0,25,162
14046,I-M253,17,2,0,2,0,9,162
12909,I-FTC3855,39,1,0,1,0,44,162
14078,I-P38,15,3,0,3,0,9,162
12676,I-FTB6825,39,1,0,1,0,75,162
11111,I-FT276480,35,1,0,1,0,60,162
15836,I-Z26728,36,1,0,1,0,44,162
9951,I-DF29,18,1,0,1,0,9,164
13331,I-FTD85849,35,1,0,1,0,13,165
9780,I-BY82727,40,1,0,1,0,19,165
8045,I-A16216,34,1,0,1,0,14,165
11078,I-FT268678,37,1,0,1,0,17,165
943,C-V9,7,13,2,11,0,53,197

Running IID PTN126...
Average Coverage: 0.3789x
#Sites covered: 835624/2868884
#Derived Loci:
5023 / 835624 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
17104,I-Y93646,35,1,0,1,0,55,205
13152,I-FTA37506,27,1,0,1,0,59,205
15285,I-P38,15,4,0,4,0,10,205
16289,I-Y303312,39,1,0,1,0,83,206
12515,I-FT403416,37,1,0,1,0,82,206
9944,I-BY3095,29,1,0,1,0,77,206
10820,I-DF29,18,3,0,3,0,10,207
9616,I-BY176594,32,1,0,1,0,22,210
8729,I-A16491,34,1,0,1,0,15,210
8602,I-A10208,36,1,0,1,0,15,210
12702,I-FT50308,25,1,0,1,0,17,210
9976,I-BY3419,24,1,0,1,0,10,210
15496,I-S2077,23,1,0,1,0,10,210
10231,I-BY51167,30,1,0,1,0,13,210
10449,I-BY66937,36,1,0,1,0,15,210
10402,I-BY64033,39,1,0,1,0,21,210
12787,I-FT6706,26,1,0,1,0,10,211
15741,I-Y133845,27,1,0,1,0,10,212
12930,I-FT9196,29,2,0,2,0,10,212
1010,C-V9,7,14,2,12,0,56,252

Running IID PTN406...
Average Coverage: 0.3987x
#Sites covered: 878674/2868884
#Derived Loci:
4372 / 878674 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
17572,I-YSC0000285,13,1,0,1,0,7,157
25485,J-ZS1713,39,1,0,1,0,45,157
23960,J-Y183473,24,1,0,1,0,61,157
15621,I-M170,14,44,0,44,0,7,158
24382,J-Y28729,24,1,0,1,0,88,158
20548,J-FT287878,52,1,0,1,0,57,158
24173,J-Y214582,52,1,0,1,0,54,158
20247,J-FT230371,54,1,0,1,0,57,158
20761,J-FT369204,51,1,0,1,0,55,158
15657,I-P38,15,6,0,6,0,7,202
10180,I-BY3095,29,1,0,1,0,68,202
11088,I-DF29,18,1,0,1,0,7,202
9518,I-BY13353,36,1,0,1,0,56,202
16171,I-Y140204,33,1,0,1,0,65,202
17577,I-Z138,20,2,0,2,0,7,203
13686,I-FTA71886,27,1,0,1,0,10,203
11176,I-FGC21991,34,1,0,1,0,10,203
15660,I-PF1123,40,1,0,1,0,19,203
15948,I-S6277,22,1,0,1,0,7,205
1030,C-V9,7,21,1,20,0,72,249

Running IID PTN231...
Average Coverage: 0.3564x
#Sites covered: 799216/2868884
#Derived Loci:
3523 / 799216 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
49040,R-FTB58732,44,1,0,1,0,16,257
52204,R-FTE50533,46,1,0,1,0,16,257
52468,R-FTE81912,47,1,0,1,0,17,257
32999,R-BY15555,46,1,0,1,0,23,257
46384,R-FT73808,45,1,0,1,0,24,257
42315,R-FT18992,49,1,0,1,0,18,257
49726,R-FTC1698,47,1,0,1,0,15,257
55130,R-Y125855,59,1,0,1,0,28,257
35402,R-BY3354,56,1,0,1,0,22,257
32105,R-BY1188,53,1,0,1,0,19,257
47409,R-FTA38452,51,1,0,1,0,21,257
32869,R-BY152550,49,1,0,1,0,18,257
56597,R-Y37962,39,1,0,1,0,13,257
40219,R-FGC49680,65,1,0,1,0,32,257
38782,R-BY94083,39,1,0,1,0,29,258
54635,R-S19342,42,2,0,2,0,13,258
32481,R-BY133523,43,1,0,1,0,13,260
36971,R-BY61743,44,1,0,1,0,13,261
32045,R-BY117000,45,1,0,1,0,13,262
36938,R-BY61482,46,3,1,2,0,13,263

Running IID PTN495...
Average Coverage: 0.3000x
#Sites covered: 698802/2868884
#Derived Loci:
3349 / 698802 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
41345,R-FT34517,44,1,0,1,0,14,215
30897,R-BY166488,48,1,0,1,0,8,215
41804,R-FT375991,47,1,0,1,0,10,215
46080,R-FTB93188,49,1,0,1,0,8,215
39843,R-FT21699,50,1,0,1,0,14,215
40555,R-FT263049,51,1,0,1,0,13,215
40323,R-FT246039,51,1,0,1,0,10,215
33010,R-BY35726,51,1,0,1,0,10,215
39238,R-FT185374,55,1,0,1,0,10,215
40873,R-FT28897,44,1,0,1,0,9,215
50938,R-S19342,42,3,1,2,0,8,215
38388,R-FT132323,57,1,0,1,0,15,215
50211,R-FTH61597,55,1,0,1,0,26,215
32844,R-BY3354,56,1,0,1,0,15,215
51730,R-Y16063,53,1,0,1,0,14,215
28987,R-A6925,55,1,0,1,0,10,215
30090,R-BY133523,43,2,0,2,0,9,217
34310,R-BY61743,44,4,0,4,0,9,219
29705,R-BY117000,45,1,0,1,0,9,223
34277,R-BY61482,46,3,0,3,0,9,224

Running IID PTN390...
Average Coverage: 0.3510x
#Sites covered: 784974/2868884
#Derived Loci:
4527 / 784974 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
4738,E-P2,12,2,0,2,0,5,88
4635,E-M35,14,32,0,32,0,5,90
210,A-Y8284,5,3,0,3,0,36,99
466,BT-M91,6,137,16,119,2,36,102
3904,E-FTB9206,26,1,0,1,0,63,122
5288,E-Y228679,29,1,0,1,0,32,122
4667,E-M78,16,20,0,20,0,5,122
5239,E-Y216284,24,1,0,1,0,35,122
5736,E-Z1919,18,1,0,1,0,5,142
2224,E-BY8085,33,1,0,1,0,36,143
4610,E-L618,19,9,0,9,0,5,143
5523,E-Y473811,34,1,0,1,0,36,144
4892,E-V13,21,23,0,22,1,5,152
5695,E-Z1057,22,1,0,1,0,5,174
4839,E-S2979,28,1,0,1,0,5,175
1999,E-BY6094,35,1,0,1,0,9,175
3835,E-FTB6188,38,1,0,1,0,7,176
5392,E-Y323301,35,1,0,1,0,7,176
973,C-V9,7,18,1,17,0,52,221
4740,E-P29,9,2,0,2,0,53,238

Running IID PTN439...
Average Coverage: 0.3532x
#Sites covered: 799009/2868884
#Derived Loci:
3146 / 799009 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
34982,R-BY3508,38,1,0,1,0,128,104
38849,R-FGC12045,40,1,0,1,0,133,104
41197,R-FT157508,53,1,0,1,0,152,104
4745,E-P177,11,2,0,2,0,6,107
4746,E-P2,12,5,0,5,0,6,109
4750,E-PF1885,12,1,0,1,0,6,109
221,A-Y8284,5,4,0,4,0,54,113
4643,E-M35,14,36,0,36,0,6,114
486,BT-M91,6,127,15,111,1,54,117
4677,E-M78,16,15,0,15,0,6,150
3612,E-FTA49406,33,1,0,1,0,29,150
4761,E-PF2438,19,1,0,1,0,51,150
4757,E-PF2179,17,2,0,2,0,6,165
4617,E-L618,19,14,0,14,0,6,167
4902,E-V13,21,18,0,18,0,6,181
5721,E-Z1057,22,1,0,1,0,6,199
4850,E-S2979,28,1,0,1,0,6,200
995,C-V9,7,14,1,13,0,69,228
4747,E-P29,9,1,0,1,0,70,241
1218,D-CTS3946,9,1,0,1,0,70,241

# Hard-code manual calls
Read-out from the above output

In [26]:
y_dct = {
    "PTN209": "R-FTG53091",
    "PTN211": "R-FTG53091",
    "PTN139": "I-FT58623",
    "PTN146": "I-FT58623",
    "PTN267": "I-FT58623",
    "PTN238": "I-DF29",
    "PTN126": "I-FT9196",
    "PTN406": "I-S6277",
    "PTN231": "R-BY61482",
    "PTN495": "R-BY61482",
    "PTN390": "E-S2979",
    "PTN439": "E-S2979"
}

### Extract Mismatching SNPs

In [35]:
%%time

df_mms_lst  = []

for iid, hpgrp in y_dct.items():
    print(f"Running IID {iid}...")
    bam_path = df_bams.loc[df_bams["iid"]==iid, "bam"].values[0]

    ### Get allele counts
    df_ch, df_der = call_y_bam(df=df1, path_bam=bam_path,
                           path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed') 
    ### Get mismatches
    df_mms = get_mismatch_snps(hpgrp, chpar=chpar, df_ch=df_ch)

    df_mms_lst.append(df_mms)

Running IID PTN209...
Average Coverage: 7.2976x
#Sites covered: 2370738/2868884
#Derived Loci:
6390 / 2370738 covered>0
Running IID PTN211...
Average Coverage: 0.3651x
#Sites covered: 820913/2868884
#Derived Loci:
4017 / 820913 covered>0
Running IID PTN139...
Average Coverage: 0.3297x
#Sites covered: 752016/2868884
#Derived Loci:
3882 / 752016 covered>0
Running IID PTN146...
Average Coverage: 0.3544x
#Sites covered: 792820/2868884
#Derived Loci:
4338 / 792820 covered>0
Running IID PTN267...
Average Coverage: 0.4835x
#Sites covered: 1004319/2868884
#Derived Loci:
4110 / 1004319 covered>0
Running IID PTN238...
Average Coverage: 0.2982x
#Sites covered: 694724/2868884
#Derived Loci:
3436 / 694724 covered>0
Running IID PTN126...
Average Coverage: 0.3789x
#Sites covered: 835624/2868884
#Derived Loci:
5023 / 835624 covered>0
Running IID PTN406...
Average Coverage: 0.3987x
#Sites covered: 878674/2868884
#Derived Loci:
4372 / 878674 covered>0
Running IID PTN231...
Average Coverage: 0.3564x
#Sites covered: 799216/2868884
#Derived Loci:
3523 / 799216 covered>0
Running IID PTN495...
Average Coverage: 0.3000x
#Sites covered: 698802/2868884
#Derived Loci:
3349 / 698802 covered>0
Running IID PTN390...
Average Coverage: 0.3510x
#Sites covered: 784974/2868884
#Derived Loci:
4527 / 784974 covered>0
Running IID PTN439...
Average Coverage: 0.3532x
#Sites covered: 799009/2868884
#Derived Loci:
3146 / 799009 covered>0
CPU times: user 26.3 s, sys: 14.6 s, total: 40.9 s
Wall time: 3min 29s

### Analyze Mismatching SNPs

In [41]:
mms = list(map(len,df_mms_lst))
mms

[29, 6, 11, 7, 16, 9, 10, 7, 14, 9, 5, 6]

In [48]:
print(f"{np.mean(mms[1:]):.3f}") ### Average Mismatches in 1x Data

9.091

In [49]:
df_mms = pd.concat(df_mms_lst)

In [70]:
df_cts = pd.value_counts(df_mms["Subgroup Name"])

/tmp/ipykernel_1938581/1535705838.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df_cts = pd.value_counts(df_mms["Subgroup Name"])

In [71]:
df_cts.to_csv("/mnt/archgen/users/hringbauer/git/y_chrom/data/OY/mm12.tsv", sep="\t")

In [62]:
df_mms

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
2127395,"MF784814,YSC0000166",Y,14116584,A,T,R-P297,NaN,26,17,0,0,0,17,0
2090274,"FGC58,MF803532",Y,7100362,T,C,R-M343,NaN,22,0,0,0,8,8,0
2090443,"FGC66,MF803527",Y,7081561,T,C,R-M343,NaN,22,0,0,0,9,9,0
2073713,"FGC280,MF786133",Y,19298321,A,G,R-UTY2,NaN,20,9,0,0,0,9,0
2075838,"MF789201,YSC0000067",Y,7133986,C,G,R-UTY2,NaN,20,0,8,0,0,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684450,"Y9964,Z9440",Y,18132698,T,C,A-V168,NaN,3,0,0,0,1,1,0
684580,CTS12370,Y,28583229,T,C,A-V168,NaN,3,0,0,0,1,1,0
684129,BY184462,Y,8055446,G,A,A-L1090,NaN,2,0,0,1,0,1,0
684138,FGC27824,Y,23139472,T,C,A-L1090,NaN,2,0,0,0,2,2,0
684204,V3167,Y,15833573,T,C,A-L1090,NaN,2,0,0,0,1,1,0

# 3) Try new single samples

In [23]:
df_bams = pd.read_csv("/mnt/archgen/users/hringbauer/git/EPIDEMIC/output/tables/autoeager_seqfull_anno.tsv", sep="\t")
print(f"Loaded {len(df_bams)} processed bam files from PTN")
df_m = df_bams[df_bams["sex"]=="m"]
print(f"Extracted {len(df_m)} males")

Loaded 414 processed bam files from PTN
Extracted 209 males

In [ ]:
df_m["iid"][-50:] # Plot a few male IIDs

### 3) Analyze single example

In [73]:
iid = "PTN238"
print(f"Running IID {iid}...")
bam_path = df_bams.loc[df_bams["iid"]==iid, "bam"].values[0]

### Do the call
df_ch, df_der = call_y_bam(df=df1, path_bam=bam_path,
                       path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed') 

### Post-process output for info for manual call
dft = div_anc_der(df_ch, df_exclude=df_ex)
dfd = dft[dft["Derived"]>dft["Ancestral"]]
display(dfd.sort_values(by="#DER in par.").tail(30))

Running IID PTN238...
Average Coverage: 0.2982x
#Sites covered: 694724/2868884
#Derived Loci:
3436 / 694724 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
43423,R-FTA27308,42,1,0,1,0,72,124
24126,N-BY99399,53,1,0,1,0,31,124
42590,R-FT67224,55,1,0,1,0,78,124
43999,R-FTA70641,50,1,0,1,0,80,124
43554,R-FTA32861,52,1,0,1,0,78,124
45368,R-FTB75363,54,1,0,1,0,87,124
28362,R-A12274,53,1,0,1,0,84,124
25774,O-CTS11725,27,1,0,1,0,66,125
14043,I-M170,14,33,0,33,0,0,127
18547,J-FT36487,46,1,0,1,0,33,127
22013,J-Y539179,44,1,0,1,0,31,127
22749,J-ZS1824,48,1,0,1,0,31,127
20844,J-HU533,51,1,0,1,0,32,127
17943,J-FT182281,52,1,0,1,0,31,127
21283,J-Y155375,28,1,0,1,0,80,127
18553,J-FT366856,29,1,0,1,0,67,127
19097,J-FTA29896,36,1,0,1,0,38,127
14078,I-P38,15,3,0,3,0,0,160
9693,I-BY70891,23,1,0,1,0,16,160
12909,I-FTC3855,39,1,0,1,0,35,160
14046,I-M253,17,2,0,2,0,0,160
12676,I-FTB6825,39,1,0,1,0,66,160
11111,I-FT276480,35,1,0,1,0,51,160
15836,I-Z26728,36,1,0,1,0,35,160
9951,I-DF29,18,1,0,1,0,0,162
13331,I-FTD85849,35,1,0,1,0,4,163
9780,I-BY82727,40,1,0,1,0,10,163
8045,I-A16216,34,1,0,1,0,5,163
11078,I-FT268678,37,1,0,1,0,8,163
943,C-V9,7,13,2,11,0,49,196

In [57]:
dfmm = get_mismatch_snps("I-M253", chpar=chpar, df_ch=df_ch)

In [58]:
dfmm

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
600278,PF3518,Y,6607318,C,T,IJ-P124,NaN,12,0,1,0,0,1,0
597522,CTS5750,Y,16467111,T,C,F-M89,F,8,0,0,0,1,1,0
597760,"MF808158,PF1911",Y,23729951,T,C,F-M89,F,8,0,0,0,1,1,0
597769,"MF806436,PF1720,TY199699",Y,17142068,T,A,F-M89,F,8,0,0,0,1,1,0
596861,Y1445,Y,2987520,C,T,CT-M168,NaN,6,0,2,0,1,2,1
595966,"V6478,Z9327",Y,17028360,T,A,A-V168,NaN,3,0,0,0,2,2,0
596059,"Y9964,Z9440",Y,18132698,T,C,A-V168,NaN,3,0,0,0,1,1,0
595796,FGC27794,Y,23049484,T,C,A-L1090,NaN,2,0,0,0,2,2,0
595851,V3167,Y,15833573,T,C,A-L1090,NaN,2,0,0,0,1,1,0

In [45]:
dfmm[~dfmm["Subgroup Name"].isin(df_ex["Subgroup Name"])]

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
564489,"L777,YSC0000248",Y,13657777,T,C,R-M269,NaN,27,0,0,0,1,1,0
550067,"FGC66,MF803527",Y,7081561,T,C,R-M343,NaN,22,0,0,0,1,1,0
533546,A5111,Y,13511050,C,G,A-L1090,NaN,2,0,1,0,0,1,0

In [59]:
df_ch[df_ch["Y-haplogroup"]=="I-M253"]

,Subgroup Name,chrom,pos,ref,alt,Y-haplogroup,YFull translation,Level,A,C,G,T,ref#,alt#
604184,"Page123,PAGES00123,Z2763",Y,14898383,G,A,I-M253,NaN,17,1,0,0,0,0,1
605549,Z2860,Y,22480517,C,A,I-M253,NaN,17,1,0,0,0,0,1

##

### Kamenice IID KNC002

In [68]:
### Do the call
df_ch, df_der = call_y_bam(df=df1, path_bam="/mnt/archgen/Autorun_eager/eager_outputs/RM/KNC/KNC139/trimmed_bam/KNC139_ss.A0101_udgnone.trimmed.bam",
                       path_bed='/mnt/archgen/users/hringbauer/git/y_chrom/data/OY_snps.bed') 

### Post-process output for info for manual call
dft = div_anc_der(df_ch, df_exclude=df_ex)
dfd =dft[dft["Derived"]>dft["Ancestral"]]
display(dfd.sort_values(by="#DER in par.").tail(30))

Average Coverage: 1.2350x
#Sites covered: 889590/2868884
#Derived Loci:
8264 / 889590 covered>0

,Branch,Level,Total_SNPs,Ancestral,Derived,Uncovered,#ANC in par.,#DER in par.
52781,R-FTC9482,56,1,0,1,0,24,352
53490,R-FTD61432,56,1,0,1,0,11,352
59648,R-Y81029,62,2,0,1,1,22,352
58596,R-Y331948,56,1,0,1,0,23,352
32481,R-A6097,50,1,0,1,0,15,352
56895,R-S3253,50,1,0,1,0,14,352
41211,R-DC858,51,1,0,1,0,13,352
34229,R-BY149318,51,1,0,1,0,15,352
45529,R-FT25395,51,1,0,1,0,5,352
48842,R-FT99153,51,1,0,1,0,21,352
55678,R-FTG74028,51,1,0,1,0,8,352
40235,R-BY78379,51,1,0,1,0,15,352
52486,R-FTC72671,51,1,0,1,0,12,352
32496,R-A6389,50,1,0,1,0,11,352
44146,R-FT183081,54,1,0,1,0,13,352
42028,R-FGC4125,54,1,0,1,0,9,352
47455,R-FT409211,47,2,0,2,0,18,353
51573,R-FTB93730,44,1,0,1,0,6,353
60630,R-Z2110,33,3,0,3,0,1,353
42164,R-FGC48353,39,1,0,1,0,4,353
34172,R-BY14600,51,1,0,1,0,6,353
32121,R-A13330,49,1,0,1,0,10,353
33480,R-BY1188,53,1,0,1,0,12,353
41091,R-CTS7556,34,2,0,2,0,1,356
36598,R-BY251,37,1,0,1,0,1,358
54160,R-FTE34250,45,1,0,1,0,13,358
57841,R-Y18850,45,1,0,1,0,6,359
37352,R-BY3717,40,1,0,1,0,1,359
58459,R-Y305501,42,1,0,1,0,1,360
1263,D-CTS3946,9,1,0,1,0,75,372

In [ ]:
R-Y305501 III KNC002, KNC006, KNC010, KNC139
R-Y439571

In [ ]:
dfmm = get_mismatch_snps("R-Y583795", chpar=chpar, df_ch=df_ch)

In [66]:
df_ch[df_ch["Y-haplogroup"]=="R-Y305501"]

Empty DataFrame
Columns: [Subgroup Name, chrom, pos, ref, alt, Y-haplogroup, YFull translation, Level, A, C, G, T, ref#, alt#]
Index: []

# Area51

In [20]:
df_m[df_m["iid"].str.contains("BMG001")]["bam"].values[0]

'/mnt/archgen/Autorun_eager/eager_outputs/SG/BMG/BMG001/merged_bams/additional/BMG001_ss_libmerged_add.bam'

In [ ]:
WSQ003

In [79]:
def exclude_snps(df_ch, df_ex, verbose=False, col="Subgroup Name"):
    """Filter SNPs from df_ch in df_ex"""

    idx= df_ch[col].isin(df_ex[col])
    df_ch2 = df_ch[~idx].copy()
    if verbose:
        print(f"Filtered to {len(df_ch2)}/{len(df_ch)}")
    return df_ch2

In [81]:
df_ch2 = exclude_snps(df_ch, df_ex, verbose=True)

Filtered to 859174/859183

In [ ]:
df_b

In [85]:
dfs[dfs["snp"].str.contains("rs5743618")]

Empty DataFrame
Columns: [snp]
Index: []

In [86]:
dfs

               snp
0       rs12562034
1        rs3934834
2        rs9442372
3        rs3737728
4        rs6687776
...            ...
475801   rs5940484
475802   rs5983658
475803    rs553678
475804    rs473491
475805    rs557132

[475806 rows x 1 columns]